### ISSUE TITLE
Code used to generate this

### ISSUE THREAD

**Issue by zmbc** [CT-Data-Collaborative/2022-block-crosswalk#3]
Hello,

Would it be possible to include the code you used to generate this crosswalk? I'd love to use it, but would like to be able to check how it was created.

Thanks!

**Comment by jillctdata** [comment]
Hi,

We used QGIS to create the crosswalk, happy to chat more over email (info@ctdata.org). What are you using it for?

Thanks!

**Comment by zmbc** [comment]
Thanks @jillctdata! I'm working on a spatial epidemiology research project, and am modeling a population structure using (in part) the [2020 Census Privacy-Protected Microdata File (PPMF)](https://www.census.gov/data/tables/2024/dec/2020-census-ppmf.html). The PPMF has block codes, but being from 2020, only old (pre-2022) county-equivalent codes.

I was hoping to use and cite your crosswalk for more transparency in my computational pipeline, but if code is not available, I will stick to using [GeoCorr 2022](https://mcdc.missouri.edu/applications/geocorr2022.html) for now, which also doesn't have public code as far as I know.

If you're at all interested in making your work more reproducible, I'd be happy to give some pointers. I'm not too familiar with QGIS but it looks like it has [scripting capabilities](https://docs.qgis.org/3.34/en/docs/user_manual/processing/modeler.html#exporting-a-model-as-a-python-script) you could use to record and replay your process, and a tool like [Snakemake](https://snakemake.readthedocs.io/en/stable/) could allow you to write out your entire processing pipeline, so it is easy for anyone to produce the files in this repository.

**Comment by jillctdata** [comment]
Thank you @zmbc for these resources! I'll look into them.
